### ISSUE TITLE
We need to add mobile only banner image ( custom field ) to Chef page

### ISSUE THREAD

**Issue by asapzulu** [asapzulu/MMB#10]
Its strange this page has no chef photo like on desktop so 

Add custom field name "Mobile only image" = image , only show this image for mobile devices  (max-width:767px)  .

  @media all and (max-width:767px) {

chef-image-mobile { width: 100%; height: auto; }
 
 }

![Screen Shot 2019-06-27 at 2 57 47 PM](https://user-images.githubusercontent.com/22117203/60244166-696d8600-98ec-11e9-9b59-c3e70b86e789.png)

**Comment by bbwstar** [comment]
Done!
