### ISSUE TITLE
Add WeChat Pop-Up in Menu

### ISSUE THREAD

**Issue by asapzulu** [asapzulu/MMB#11]
If the user clicks the WeChat Icon we should open some lightbox, fancybox I think your using. 

![Screen Shot 2019-06-27 at 3 05 17 PM](https://user-images.githubusercontent.com/22117203/60244696-83f42f00-98ed-11e9-96f4-04b28efd45fb.png)

So make fancybox modal.  I am attaching example QR code:  image its image size is 378px by 378px  

![example-qrcode](https://user-images.githubusercontent.com/22117203/60244834-d9304080-98ed-11e9-9a65-f0a06468cc47.png)

If the user clicks the QR code image inside the fancybox it will close the lightbox ( we dont need a close button, just click anywhere in the image will close it ).

So;

add function for fancybox lightbox for WeChat.
add custom field ( WeChat QR code image ), so we can upload the WeChat QR code.

The QR code will be absolutely centered. The WeChat QR code  image size is 378px by 378px 

Example the lightbox QR page can look like this. 

![Screen Shot 2019-06-27 at 3 04 59 PM](https://user-images.githubusercontent.com/22117203/60244712-8c4c6a00-98ed-11e9-8e13-f6751cbd505a.png)

**Comment by bbwstar** [comment]
Done!
