### ISSUE TITLE
Make Slideshow navigator Position Relative, now its clashing with text

### ISSUE THREAD

**Issue by asapzulu** [asapzulu/MMB#12]
On the Events page template example events page, make the slideshow navigator container area position relative not fixed.

It should follow the height content of each tab, please becareful, because each of the 4 tabs content has different height :) 

![Screen Shot 2019-06-27 at 3 13 11 PM](https://user-images.githubusercontent.com/22117203/60245090-5bb90000-98ee-11e9-87f8-0601ca1b0f5c.png)

**Comment by bbwstar** [comment]
Done!
