### ISSUE TITLE
All PDF upload file links should open in ARI Fancy Lightbox 

### ISSUE THREAD

**Issue by asapzulu** [asapzulu/MMB#13]
I installed the plugin for you. Now you can just change the code for all PDF links for example:

![Screen Shot 2019-06-27 at 3 16 31 PM](https://user-images.githubusercontent.com/22117203/60245379-15b06c00-98ef-11e9-9053-b5f02213b7cf.png)

The lightbox is the same one you used for The Cut, remember? 

![Screen Shot 2019-06-27 at 3 18 02 PM](https://user-images.githubusercontent.com/22117203/60245393-1e08a700-98ef-11e9-9ddc-3ad58a2eb407.png)

**Comment by bbwstar** [comment]
Done!
