### ISSUE TITLE
On Fixed No scrolling desktop pages when the browser window is shorter the content is hidden.

### ISSUE THREAD

**Issue by asapzulu** [asapzulu/MMB#15]
On Fixed No scrolling desktop pages when the browser window is shorter the content is hidden.

How can we find a good solution for this. Just for part of the page... Maybe resize the fonts and images ? Because some people have small height laptops especially Windows 13 inch laptops.

How you think we can fix this? Tell us your best solution idea. 

![Screen Shot 2019-06-29 at 9 34 51 AM](https://user-images.githubusercontent.com/22117203/60378242-0c8be000-9a52-11e9-97b1-1074e3d9e309.png)

**Comment by asapzulu** [comment]
Maybe you can do this ?
--------------------------
.event-section {
    padding: 11vh 0 10vh;
}


It will end up looking like this:

![Screen Shot 2019-06-29 at 9 44 44 AM](https://user-images.githubusercontent.com/22117203/60378275-963bad80-9a52-11e9-8668-5830042daed1.png)


![Screen Shot 2019-06-29 at 9 44 22 AM](https://user-images.githubusercontent.com/22117203/60378279-a5baf680-9a52-11e9-9186-0cf914e6fe50.png)

**Comment by bbwstar** [comment]
I already applied style you provided.
Please check now. but I don't think that will work perfectly about smaller height pc.

**Comment by bbwstar** [comment]
> I already applied style you provided.
> Please check now. but I don't think that will work perfectly about smaller height pc.
> So I am thinking about some js effect.
