### ISSUE TITLE
Awards Page  - Help Echo PHP in template php. 

### ISSUE THREAD

**Issue by asapzulu** [asapzulu/MMB#16]
Could you help us to write the PHP to echo the following parts, no need to style it.  The php file is in the FTP /wp-content/themes/Bund/template-awards.php 

The content for Awards page example live is here: http://mmbund.com/#/awards/ of the old site.

The Design we want to get is this here attached below:
![Awards-1](https://user-images.githubusercontent.com/22117203/60517660-a2559280-9d12-11e9-964d-a779eddfc24c.jpg)

We already made the custom fields in the back-end called " Awards "
![Screen Shot 2019-07-02 at 9 48 17 PM](https://user-images.githubusercontent.com/22117203/60517981-2d368d00-9d13-11e9-81e5-7b2b66eee708.png)

We already made the page > Awards 

But the "Old Awards" section, the "MR & MRS BUND VIP"  need to echo them in PHP ( write the PHP if... echo ... ) 

![Screen Shot 2019-07-02 at 9 48 00 PM](https://user-images.githubusercontent.com/22117203/60517994-34f63180-9d13-11e9-9c11-053fec4255c9.png)

![Awards-1-notes](https://user-images.githubusercontent.com/22117203/60517854-f791a400-9d12-11e9-9334-79f1eb018979.jpg)

![Screen Shot 2019-07-02 at 9 46 55 PM](https://user-images.githubusercontent.com/22117203/60517877-01b3a280-9d13-11e9-8916-89185119755a.png)

**Comment by bbwstar** [comment]
I already outputted custom fields.
I am not sure if I have to make same style as well.
Please let me know if you need more help from me.

**Comment by asapzulu** [comment]
Hi it looks done and perfect ! :) Thank you.
