### ISSUE TITLE
Load Google Analytics Locally 

### ISSUE THREAD

**Issue by asapzulu** [asapzulu/MMB#6]
As you know Google analytics is blocked in China. We would need to host the analytics.js file inside our theme so we can still use Google Analytics.

![Screen Shot 2019-06-27 at 1 00 35 PM](https://user-images.githubusercontent.com/22117203/60235807-97969a00-98db-11e9-85b2-1bb62c03b5eb.png)

**Comment by bbwstar** [comment]
Done!
