### ISSUE TITLE
Hide the "Bookings" and "Contact" links when in mobile devices.

### ISSUE THREAD

**Issue by asapzulu** [asapzulu/MMB#7]
![Screen Shot 2019-06-27 at 1 04 31 PM](https://user-images.githubusercontent.com/22117203/60235992-4935cb00-98dc-11e9-9cd1-65168c00e91d.png)

-------
CSS would be like:
------

 @media all and (max-width:959px) {

.top-right-menu , .footer-menu {display:none;}
 
 }

**Comment by bbwstar** [comment]
Done!
