### ISSUE TITLE
Hard to click make clickable area bigger

### ISSUE THREAD

**Issue by asapzulu** [asapzulu/MMB#8]
Can you increase the clickable area, maybe add "padding: " to the <a> link attribute because now its hard to click each slide. You need your mouse to be exactly on the line. As you know people on mobile phones need more space to click and also on desktop its not very user friendly. 

![Screen Shot 2019-06-27 at 1 53 42 PM](https://user-images.githubusercontent.com/22117203/60240421-7b96f680-98e3-11e9-98b7-6c92c6023e71.png)

**Comment by bbwstar** [comment]
Done!
