### ISSUE TITLE
Logo only sticky ontop on homepage. Other pages please make the logo position relative.

### ISSUE THREAD

**Issue by asapzulu** [asapzulu/MMB#9]
The problem is now the logo on inside pages which may scroll the logo is always interupting the user, the logo is always clashing with the text. 

Don't change homepage logo sticky like now. Logo only sticky ontop on homepage ( page = front-page ).

Please change and make the logo position relative on inside page.  Other pages example: /events or all other inside pages, please make the logo position relative.

![Screen Shot 2019-06-27 at 2 34 51 PM](https://user-images.githubusercontent.com/22117203/60242795-2f4eb500-98e9-11e9-85ed-5e6f31f4b0b8.png)

![Screen Shot 2019-06-27 at 2 38 38 PM](https://user-images.githubusercontent.com/22117203/60243057-f2cf8900-98e9-11e9-984a-0b33081062df.png)

**Comment by bbwstar** [comment]
Done!
